'use client';
import { GeneratedPaper } from '@/types';

interface Props {
  paper: GeneratedPaper;
}

export default function QuestionPaper({ paper }: Props) {
  return (
    <div id="question-paper" className="bg-white rounded-2xl border border-gray-200 p-8 max-w-3xl mx-auto">
      {/* Header */}
      <div className="text-center border-b border-gray-200 pb-5 mb-5">
        <h1 className="text-xl font-bold text-gray-900">Delhi Public School, Sector-4, Bokaro</h1>
        <p className="text-sm text-gray-600 mt-1">Subject: {paper.subject}</p>
        <p className="text-sm text-gray-600">Class: {paper.className}</p>
      </div>

      {/* Meta Row */}
      <div className="flex justify-between text-sm text-gray-700 mb-4">
        <span>Time Allowed: <strong>{paper.timeAllowed}</strong></span>
        <span>Maximum Marks: <strong>{paper.maxMarks}</strong></span>
      </div>

      {/* General Instructions */}
      {paper.generalInstructions && (
        <p className="text-sm text-gray-600 italic mb-5">{paper.generalInstructions}</p>
      )}

      {/* Student Info */}
      <div className="flex flex-wrap gap-8 mb-6 text-sm text-gray-700">
        <span>Name: <span className="border-b border-gray-400 inline-block w-36">&nbsp;</span></span>
        <span>Roll Number: <span className="border-b border-gray-400 inline-block w-24">&nbsp;</span></span>
        <span>Class/Section: <span className="border-b border-gray-400 inline-block w-24">&nbsp;</span></span>
      </div>

      {/* Sections */}
      {paper.sections.map((section, si) => (
        <div key={si} className="mb-8" data-pdf-section={si}>
          <div className="mb-3">
            <h2 className="text-base font-bold text-gray-900">{section.sectionName}</h2>
            <p className="text-xs font-semibold text-gray-600 uppercase tracking-wide mt-0.5">{section.questionType}</p>
            {section.instruction && (
              <p className="text-sm text-gray-500 italic mt-0.5">{section.instruction}</p>
            )}
          </div>

          <ol className="space-y-4">
            {section.questions.map((q) => (
              <li key={q.questionNumber} className="flex gap-3">
                <span className="text-sm font-medium text-gray-800 flex-shrink-0 w-6">{q.questionNumber}.</span>
                <div className="flex-1">
                  <div className="flex flex-wrap items-start gap-2 mb-1">
                    <p className="text-sm text-gray-800 flex-1">{q.questionText}</p>
                    <div className="flex items-center gap-1.5 flex-shrink-0">
                      {q.difficulty && (
                        <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded-full ${
                          q.difficulty.toLowerCase() === 'easy'
                            ? 'bg-green-50 text-green-600'
                            : q.difficulty.toLowerCase() === 'moderate' || q.difficulty.toLowerCase() === 'medium'
                            ? 'bg-amber-50 text-amber-600'
                            : 'bg-red-50 text-red-500'
                        }`}>
                          {q.difficulty}
                        </span>
                      )}
                      <span className="text-[11px] text-gray-400">[{q.marks} {q.marks === 1 ? 'Mark' : 'Marks'}]</span>
                    </div>
                  </div>
                  {q.options && q.options.length > 0 && (
                    <ul className="mt-1.5 space-y-1 pl-1">
                      {q.options.map((opt, oi) => (
                        <li key={oi} className="text-sm text-gray-700">{opt}</li>
                      ))}
                    </ul>
                  )}
                </div>
              </li>
            ))}
          </ol>
        </div>
      ))}

      {/* Answer Key */}
      {paper.answerKey && paper.answerKey.length > 0 && (
        <div className="border-t border-gray-200 pt-5 mt-4">
          <h2 className="text-base font-bold text-gray-900 mb-3">Answer Key</h2>
          <ol className="space-y-2">
            {paper.answerKey.map((ak) => (
              <li key={ak.questionNumber} className="text-sm text-gray-700">
                <span className="font-medium">{ak.questionNumber}.</span>{' '}
                {ak.answer}
              </li>
            ))}
          </ol>
        </div>
      )}

      <p className="text-center text-[11px] text-gray-400 mt-8 border-t border-gray-100 pt-4">
        End of Question Paper — Generated by VedaAI
      </p>
    </div>
  );
}
